# WEB SCRAPING â€“ ASSIGNMENT 4

1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

Importing necessary libraries

In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\programdata\anaconda3\lib\site-packages (4.1.3)
Requirement already satisfied: trio-websocket~=0.9 in c:\programdata\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: trio~=0.17 in c:\programdata\anaconda3\lib\site-packages (from selenium) (0.20.0)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\programdata\anaconda3\lib\site-packages (from selenium) (1.26.7)
Requirement already satisfied: cffi>=1.14 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.6)
Requirement already satisfied: async-generator>=1.9 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: outcome in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: attrs>=19.2.0 in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: sortedcontainers in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\programdata\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.2)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\programdata\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\programdata\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\programdata\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\programdata\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.8)
Requirement already satisfied: certifi in c:\programdata\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: six>=1.5.2 in c:\programdata\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.16.0)

WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -mpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -arkupsafe (c:\programdata\anaconda3\lib\site-packages)

Requirement already satisfied: h11<1,>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)

In [2]:
# Importing all the required libraries
from selenium import webdriver
import warnings
warnings.filterwarnings("ignore")
import time
from bs4 import BeautifulSoup
import re
import pandas as pd
import selenium
from bs4 import BeautifulSoup
import time
from selenium import webdriver
import requests
import re
from selenium.common.exceptions import NoSuchElementException, StaleElementReferenceException,ElementNotInteractableException
from selenium.webdriver.support.ui import WebDriverWait

In [19]:
# Connecting to the webdriver
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(3)

# Getting the webpage of mentioned url 
url=('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')
driver.get(url)

In [21]:
# Creating empty list for scaping the data

Rank = []
Name = []
Artist = []
Upload_Date = []
Views = []

In [23]:
# Scraping Rank of the videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# Scraoing Name of the videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")
    
# Scraping Artist of the video
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")

# Scraping Uploaded date of the video
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")
# Scraping Views of videos
try:
    for i in driver.find_elements_by_xpath("//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
        Upload_Date.append(i.text)
except NoSuchElementException:
    Upload_Date.append("_")
    
# Creating DataFrame fr scraped data
Wiki = pd.DataFrame({})
Wiki['Rank']=Rank
Wiki['Name']=Name
Wiki['Artist']=Artist
Wiki['Upload Date']=Upload_Date
Wiki['Views(billions)']=Views

# Removing stray numbers from Name column
Wiki.Name = Wiki.Name.apply(lambda x:x[:-4].strip('"'))
Wiki

,Rank,Name,Artist,Upload Date,Views(billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.80
1,2.,Despacito,Luis Fonsi,"January 12, 2017",7.87
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.37
3,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.74
4,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.54
5,6.,Bath Song,Cocomelon â€“ Nursery Rhymes,"May 2, 2018",5.44
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.67
7,8.,Uptown Funk,Mark Ronson,"November 19, 2014",4.60
8,9.,Learning Colors â€“ Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.58
9,10.,Masha and the Bear â€“ Recipe for Disaster,Get Movies,"January 31, 2012",4.50
10,11.,Gangnam Style,Psy,"July 15, 2012",4.45
11,12.,Wheels on the Bus,Cocomelon â€“ Nursery Rhymes,"May 24, 2018",4.12
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.95
13,14.,Sugar,Maroon 5,"January 14, 2015",3.71
14,15.,Roar,Katy Perry,"September 5, 2013",3.60
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.59
16,17.,Sorry,Justin Bieber,"October 22, 2015",3.55
17,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.46
18,19.,Axel F,Crazy Frog,"June 16, 2009",3.38
19,20.,Girls Like You,Maroon 5,"May 31, 2018",3.30
20,21.,Faded,Alan Walker,"December 3, 2015",3.29
21,22.,Dark Horse,Katy Perry,"February 20, 2014",3.29
22,23.,Baa Baa Black Sheep,Cocomelon â€“ Nursery Rhymes,"June 25, 2018",3.26
23,24.,Let Her Go,Passenger,"July 25, 2012",3.24
24,25.,Bailando,Enrique Iglesias,"April 11, 2014",3.22
25,26.,Lean On,Major Lazer,"March 22, 2015",3.22
26,27.,Perfect,Ed Sheeran,"November 9, 2017",3.18
27,28.,Shake It Off,Taylor Swift,"August 18, 2014",3.18
28,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.16
29,30.,Mi Gente,J Balvin,"June 29, 2017",3.09
30,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.80
31,2.,Despacito,Luis Fonsi,"January 12, 2017",7.87
32,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.37
33,4.,Shape of You,Ed Sheeran,"January 30, 2017",5.74
34,5.,See You Again,Wiz Khalifa,"April 6, 2015",5.54
35,6.,Bath Song,Cocomelon â€“ Nursery Rhymes,"May 2, 2018",5.44
36,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",4.67
37,8.,Uptown Funk,Mark Ronson,"November 19, 2014",4.60
38,9.,Learning Colors â€“ Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.58
39,10.,Masha and the Bear â€“ Recipe for Disaster,Get Movies,"January 31, 2012",4.50
40,11.,Gangnam Style,Psy,"July 15, 2012",4.45
41,12.,Wheels on the Bus,Cocomelon â€“ Nursery Rhymes,"May 24, 2018",4.12
42,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",3.95
43,14.,Sugar,Maroon 5,"January 14, 2015",3.71
44,15.,Roar,Katy Perry,"September 5, 2013",3.60
45,16.,Counting Stars,OneRepublic,"May 31, 2013",3.59
46,17.,Sorry,Justin Bieber,"October 22, 2015",3.55
47,18.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.46
48,19.,Axel F,Crazy Frog,"June 16, 2009",3.38
49,20.,Girls Like You,Maroon 5,"May 31, 2018",3.30
50,21.,Faded,Alan Walker,"December 3, 2015",3.29
51,22.,Dark Horse,Katy Perry,"February 20, 2014",3.29
52,23.,Baa Baa Black Sheep,Cocomelon â€“ Nursery Rhymes,"June 25, 2018",3.26
53,24.,Let Her Go,Passenger,"July 25, 2012",3.24
54,25.,Bailando,Enrique Iglesias,"April 11, 2014",3.22
55,26.,Lean On,Major Lazer,"March 22, 2015",3.22
56,27.,Perfect,Ed Sheeran,"November 9, 2017",3.18
57,28.,Shake It Off,Taylor Swift,"August 18, 2014",3.18
58,29.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.16
59,30.,Mi Gente,J Balvin,"June 29, 2017",3.09

2. Scrape the details team Indiaâ€™s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1
st ODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through cod

In [7]:
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(3)

In [8]:
url = "https://www.bcci.tv/"
driver.get(url)
time.sleep(2)

In [9]:
button=driver.find_element_by_xpath('//button[@class="cookie__accept btn btn-primary"]')
button.click()

In [10]:

# click on "International" button to expand it
driver.find_element_by_xpath("/html/body/nav/div[1]/div[2]/ul[1]/li[2]").click()

In [11]:
# click on 'Fixtures'
driver.find_element_by_xpath("/html/body/div[2]/div[1]/div/ul/li[1]").click()

In [12]:
# click on 'More Fixtures'
driver.find_element_by_xpath('/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/div/button').click()

In [20]:
#Creating Empty Listmatch = []
match = []
series = []
place = []
date = []
time = []

In [21]:
try:
    for i in driver.find_elements_by_xpath('//span[@class="ng-binding"]'):
        match.append(i.text)
except NoSuchElementException:
    match.append("-")
    
try:
    for i in driver.find_elements_by_xpath('//span[@class="matchOrderText ng-binding ng-scope"]'):
        series.append(i.text.split('-')[0])
except NoSuchElementException:
    series.append("-")
    
try:
    for i in driver.find_elements_by_xpath('//span[@class="ng-binding ng-scope"]'):
        place.append(i.text)
except NoSuchElementException:
    place.append("-")
    
try:
    for i in driver.find_elements_by_xpath('//h5[@class="ng-binding"]'):
        date.append(i.text)
except NoSuchElementException:
    date.append("-")
    
try:
    for i in driver.find_elements_by_xpath('//h5[@class="text-right ng-binding"]'):
        time.append(i.text)
except NoSuchElementException:
    time.append("-")

In [22]:
df = pd.DataFrame({'Match Title':match,'Series':series,'Venue':place,'Date':date,'time':time})
df

,Match Title,Series,Venue,Date,time
0,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,1st T20I,"Rangiri Dambulla International Stadium,",23 JUN 2022,2:30 PM IST
1,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,2nd T20I,"Rangiri Dambulla International Stadium,",25 JUN 2022,2:30 PM IST
2,INDIA TOUR OF IRELAND T20 SERIES 2022,1st T20I,"The Village,",26 JUN 2022,9:00 PM IST
3,INDIA WOMEN TOUR OF SRI LANKA T20 SERIES 2022,3rd T20I,"Rangiri Dambulla International Stadium,",27 JUN 2022,2:30 PM IST
4,INDIA TOUR OF IRELAND T20 SERIES 2022,2nd T20I,"The Village,",28 JUN 2022,9:00 PM IST
5,INDIA WOMEN TOUR OF SRI LANKA ODI SERIES 2022,1st ODI,"Pallekele International Cricket Stadium,",1 JUL 2022,10:00 AM IST
6,INDIA TOUR OF ENGLAND TEST SERIES 2021,5th Test,"Edgbaston,",1 JUL 2022,3:30 PM IST
7,INDIA WOMEN TOUR OF SRI LANKA ODI SERIES 2022,2nd ODI,"Pallekele International Cricket Stadium,",4 JUL 2022,10:00 AM IST

In [23]:
driver.close()

3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/
You need to find following details:
A) Name
B) Description
Note: - From guru99 home page you have to reach to selenium exception handling page through code.

In [39]:
driver=webdriver.Chrome("chromedriver.exe")
time.sleep(3)

In [40]:
url = "https://www.guru99.com/"
driver.get(url)
time.sleep(2)

In [41]:
search_bar = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[1]/div/table/tbody/tr/td[1]/input")
search_bar.send_keys("selenium exception handling")
search_btn = driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/form/table/tbody/tr/td[2]/button")
search_btn.click()
time.sleep(2)

In [42]:
link = driver.find_element_by_xpath('//div[@class="gsc-expansionArea"]//div//a')
page_links = link.get_attribute("href")

driver.get(page_links)
time.sleep(3)

Name = []
for i in driver.find_elements_by_xpath('//table[@class="table table-striped"]//tr//td[1]')[1:]:
    Name.append(i.text)
    
Description = []
for i in driver.find_elements_by_xpath('//table[@class="table table-striped"]//tr//td[2]')[1:]:
    Description.append(i.text)

In [43]:
df = pd.DataFrame({'Name':Name,'Description':Description})
df

,Name,Description
0,ElementNotSelectableException,This Selenium exception occurs when an element...
1,NoSuchElementException,This Exception occurs if an element could not ...
2,NoSuchFrameException,This Exception occurs if the frame target to b...
3,NoAlertPresentException,This Exception occurs when you switch to no pr...
4,NoSuchWindowException,This Exception occurs if the window target to ...
5,StaleElementReferenceException,This Selenium exception occurs happens when th...
6,SessionNotFoundException,The WebDriver is acting after you quit the bro...
7,TimeoutException,Thrown when there is not enough time for a com...
8,WebDriverException,This Exception takes place when the WebDriver ...
9,ConnectionClosedException,This type of Exception takes place when there ...
10,ElementClickInterceptedException,The command may not be completed as the elemen...
11,ElementNotInteractableException,This Selenium exception is thrown when any ele...
12,ErrorInResponseException,This happens while interacting with the Firefo...
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
14,ImeActivationFailedException,This expectation will occur when IME engine ac...
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certif...
17,InvalidArgumentException,It occurs when an argument does not belong to ...
18,InvalidCookieDomainException,This happens when you try to add a cookie unde...
19,InvalidCoordinatesException,This type of Exception matches an interacting ...
20,InvalidElementStateExceptio,It occurs when command canâ€™t be finished when ...
21,InvalidSessionIdException,This Exception took place when the given sessi...
22,InvalidSwitchToTargetException,This occurs when the frame or window target to...
23,JavascriptException,This issue occurs while executing JavaScript g...
24,JsonException,It occurs when you afford to get the session w...
25,NoSuchAttributeException,This kind of Exception occurs when the attribu...
26,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching ...
29,NotFoundException,This Exception is a subclass of WebDriverExcep...
30,RemoteDriverServerException,This Selenium exception is thrown when the ser...
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be suc...
33,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
34,UnexpectedTagNameException,Happens if a support class did not get a web e...
35,UnhandledAlertException,This expectation occurs when there is an alert...
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
37,UnknownMethodException,This Exception happens when the requested comm...
38,UnreachableBrowserException,This Exception occurs only when the browser is...
39,UnsupportedCommandException,This occurs when remote WebDriver does nâ€™t sen...

In [44]:
driver.close()

4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)
D) GSDP(17-18)
E) Share(2017)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code

In [45]:
driver= webdriver.Chrome("chromedriver.exe")

In [46]:
url = "https://www.statisticstimes.com/"
driver.get(url)

In [48]:
economy = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/button")
economy.click()
india = driver.find_element_by_xpath("/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
india.click()
time.sleep(2)

GDP_india = driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP_india.click()
time.sleep(3)

In [49]:
rank = []
state = []
GSDP = []
GSDP1 = []
share = []
GDP = []

In [50]:
for i in driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]//tbody//tr//td[1]'):
    rank.append(i.text)
    
for i in driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]//tbody//tr//td[2]'):
    state.append(i.text)
    
for i in driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]//tbody//tr//td[3]'):
    GSDP.append(i.text)
    
for i in driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]//tbody//tr//td[4]'):
    GSDP1.append(i.text)
    
for i in driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]//tbody//tr//td[5]'):
    share.append(i.text)
    
for i in driver.find_elements_by_xpath('//div[@id="table_id_wrapper"]//tbody//tr//td[6]'):
    GDP.append(i.text)

In [51]:
df = pd.DataFrame({'Rank':rank,'State':state,'GSDP(19-20)':GSDP,'GSDP(18-19)':GSDP1,'Share':share,'GDP':GDP})
df

   Rank                      State GSDP(19-20) GSDP(18-19)   Share      GDP
0     1                Maharashtra           -   2,632,792  13.94%  399.921
1     2                 Tamil Nadu   1,845,853   1,630,208   8.63%  247.629
2     3              Uttar Pradesh   1,687,818   1,584,764   8.39%  240.726
3     4                    Gujarat           -   1,502,899   7.96%  228.290
4     5                  Karnataka   1,631,977   1,493,127   7.91%  226.806
5     6                West Bengal   1,253,832   1,089,898   5.77%  165.556
6     7                  Rajasthan   1,020,989     942,586   4.99%  143.179
7     8             Andhra Pradesh     972,782     862,957   4.57%  131.083
8     9                  Telangana     969,604     861,031   4.56%  130.791
9    10             Madhya Pradesh     906,672     809,592   4.29%  122.977
10   11                     Kerala           -     781,653   4.14%  118.733
11   12                      Delhi     856,112     774,870   4.10%  117.703
12   13                    Haryana     831,610     734,163   3.89%  111.519
13   14                      Bihar     611,804     530,363   2.81%   80.562
14   15                     Punjab     574,760     526,376   2.79%   79.957
15   16                     Odisha     521,275     487,805   2.58%   74.098
16   17                      Assam           -     315,881   1.67%   47.982
17   18               Chhattisgarh     329,180     304,063   1.61%   46.187
18   19                  Jharkhand     328,598     297,204   1.57%   45.145
19   20                Uttarakhand           -     245,895   1.30%   37.351
20   21            Jammu & Kashmir           -     155,956   0.83%   23.690
21   22           Himachal Pradesh     165,472     153,845   0.81%   23.369
22   23                        Goa      80,449      73,170   0.39%   11.115
23   24                    Tripura      55,984      49,845   0.26%    7.571
24   25                 Chandigarh           -      42,114   0.22%    6.397
25   26                 Puducherry      38,253      34,433   0.18%    5.230
26   27                  Meghalaya      36,572      33,481   0.18%    5.086
27   28                     Sikkim      32,496      28,723   0.15%    4.363
28   29                    Manipur      31,790      27,870   0.15%    4.233
29   30                   Nagaland           -      27,283   0.14%    4.144
30   31          Arunachal Pradesh           -      24,603   0.13%    3.737
31   32                    Mizoram      26,503      22,287   0.12%    3.385
32   33  Andaman & Nicobar Islands           -           -       -        -

In [52]:
driver.close()

5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [5]:
#Activating the chrome browser
driver = webdriver.Chrome("chromedriver.exe")

In [6]:
#getting the specified url
url = "https://github.com/"
driver.get(url)
time.sleep(3)

In [8]:
#Getting explore button and clicking on it
explore = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details").click()

#Selecting trending option
trend_url = driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [9]:
#Creating empty list
repo_urls = []
rep_title = []
Description = []
Contributors = []
Language = []
lang = []

In [13]:
#Fetching urls for each repository
repository = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    repo_urls.append(i.get_attribute("href"))

    
#Scraping data of repository title
title = driver.find_elements_by_xpath("//h1[@class = 'h3 lh-condensed']")
for i in title:
    rep_title.append(i.text)

    
#Scraping data from every repository page
for i in repo_urls:
    driver.get(i)
    time.sleep(3)
    
    
    #Scraping data of decription
    try:
        desc = driver.find_element_by_xpath("//p[@cclass='col-9 color-fg-muted my-1 pr-4']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    #Scraping data of contributors
    try:
        cont_tags = driver.find_element_by_xpath("//*[contains(text(),'    Contributors ')]")
        Contributors.append(cont_tags.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
     #fetching Languages used
    try:
        for i in driver.find_elements_by_xpath("//span[@class='d-inline-block ml-0 mr-3']"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')

In [15]:
#DATA FRAMEING
Github=pd.DataFrame({})
Github['Repository title'] = rep_title[:50]
Github['Repository description'] = Description[:50]
Github['Contributors count'] = Contributors[:50]
Github['Language used'] = Language[:50]

In [16]:
#Printing data frame
Github

,Repository title,Repository description,Contributors count,Language used
0,mingrammer / diagrams,-,104,[]
1,hashicorp / nomad,-,556,[]
2,facebook / lexical,-,98,[]
3,girliemac / a-picture-is-worth-a-1000-words,-,2,[]
4,WenchaoD / FSCalendar,-,22,[]
5,PrefectHQ / prefect,-,311,[]
6,Reiten966 / Polyformer,-,3,[]
7,hashicorp / hcl,-,72,[]
8,pittcsc / Summer2023-Internships,-,219,[]
9,Technawi / SOC-Analyst-Diploma,-,-,[]
10,apache / hbase,-,377,[]
11,codeedu / imersao8,-,2,[]
12,go-gorm / gorm,-,305,[]
13,elixir-ecto / ecto,-,662,[]
14,milvus-io / milvus,-,183,[]
15,knative / serving,-,242,[]
16,Azure / azure-sdk-for-java,-,454,[]
17,Alamofire / Alamofire,-,240,[]
18,OAI / OpenAPI-Specification,-,198,[]
19,terraform-aws-modules / terraform-aws-alb,-,49,[]
20,google / googletest,-,356,[]
21,fastlane / fastlane,-,"1,221",[]
22,sourcegraph / sourcegraph,-,274,[]
23,woocommerce / woocommerce,-,"1,165",[]
24,firebase / firebase-ios-sdk,-,177,[]
25,mingrammer / diagrams,-,104,[]
26,hashicorp / nomad,-,556,[]
27,facebook / lexical,-,98,[]
28,girliemac / a-picture-is-worth-a-1000-words,-,2,[]
29,WenchaoD / FSCalendar,-,22,[]
30,PrefectHQ / prefect,-,311,[]
31,Reiten966 / Polyformer,-,3,[]
32,hashicorp / hcl,-,72,[]
33,pittcsc / Summer2023-Internships,-,219,[]
34,Technawi / SOC-Analyst-Diploma,-,-,[]
35,apache / hbase,-,377,[]
36,codeedu / imersao8,-,2,[]
37,go-gorm / gorm,-,305,[]
38,elixir-ecto / ecto,-,662,[]
39,milvus-io / milvus,-,183,[]
40,knative / serving,-,242,[]
41,Azure / azure-sdk-for-java,-,454,[]
42,Alamofire / Alamofire,-,240,[]
43,OAI / OpenAPI-Specification,-,198,[]
44,terraform-aws-modules / terraform-aws-alb,-,49,[]
45,google / googletest,-,356,[]
46,fastlane / fastlane,-,"1,221",[]
47,sourcegraph / sourcegraph,-,274,[]
48,woocommerce / woocommerce,-,"1,165",[]
49,firebase / firebase-ios-sdk,-,177,[]

6. Scrape the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [30]:
# Connecting to the webdriver
driver = webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.billboard.com/')
driver.get(url)

In [35]:
menu=driver.find_element_by_xpath("/html/body/div[3]/header/div[1]/div/div/div[1]/button").click()

In [36]:
list=driver.find_element_by_xpath("/html/body/div[3]/div[6]/div/div/div/ul/li[1]/h3/button").click()

In [37]:
#Clicking on charts
charts=driver.find_element_by_xpath("/html/body/div[3]/div[6]/div/div/div/ul/li[1]/ul/li[2]").click()

In [39]:
# Creating empty lists
Song_Name = []
Artist_Name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

# Getting urls for top 100 songs
urls = driver.find_element_by_xpath("/html/body/div[3]/main/div[2]/div[2]/div/div[1]/div[1]/div[1]/div/div[2]/h3/a")
page_url = urls.get_attribute("href")
driver.get(page_url)
time.sleep(4)

# Scraping data of song names
for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__song text--truncate color--primary']"):
    Song_Name.append(i.text)
    
# Scraping data of artist names
for i in driver.find_elements_by_xpath("//span[@class='chart-element__information__artist text--truncate color--secondary']"):
    Artist_Name.append(i.text)
    
# Scraping data of last week ranks
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--last']"):
    Last_week_rank.append(i.text)
    
# Scraping data of peak rank
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--peak']"):
    Peak_rank.append(i.text)
    
# Scraping data of weeks on board
for i in driver.find_elements_by_xpath("//div[@class='chart-element__meta text--center color--secondary text--week']"):
    Weeks_on_board.append(i.text)
    
# Creating dataframe for scraped data
billboard=pd.DataFrame({})
billboard['Name'] = Song_Name
billboard['Artist'] = Artist_Name
billboard['Last week rank'] = Last_week_rank
billboard['Peak rank'] = Peak_rank
billboard['Weeks on board'] = Weeks_on_board
billboard

Empty DataFrame
Columns: [Name, Artist, Last week rank, Peak rank, Weeks on board]
Index: []

7. Scrape the details of Data science recruiters from naukri.com.
Url = https://www.naukri.com/
You have to find the following details:
A) Name
B) Designation
C) Company
D) Skills they hire for
E) Location
Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and
click on search. All this should be done through code

In [49]:
# Connecting to the webdriver
driver = webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.naukri.com/browse-jobs')
driver.get(url)
time.sleep(2)

In [50]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element_by_xpath("//a[@title='Search Recruiters']")
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [51]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element_by_xpath("//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element_by_xpath("//button[@class='fl qsbSrch blueBtn']").click()     
time.sleep(3)

In [52]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

#Scraping data of Names
for i in driver.find_elements_by_xpath("//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)


#Scraping data of Designation
for i in driver.find_elements_by_xpath("//span[@class='ellipsis clr']"):
    Designation.append(i.text)
time.sleep(3)

#Scraping data of company name
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)
time.sleep(3)
    
#scraping data of Skills 
for i in driver.find_elements_by_xpath("//div[@class='hireSec highlightable']"):
    try:
        if i.text == "Not Specified": raise NoSuchElementException
        Skills.append(i.text)
    except NoSuchElementException:
        Skills.append('-')
    time.sleep(3)

#Scraping data of locations
for i in driver.find_elements_by_xpath("//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name[:50]
Naukri['Designation'] = Designation[:50]
Naukri['Company'] = Company[:50]
Naukri['Skills'] = Skills[:50]
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Anik Agrawal
10,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Company Recruiter
11,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Ahmedabad
12,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",subhas patel
13,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Founder CEO
14,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",UK - (london)
15,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Abhishek - Only Analytics Hiring - India and
16,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Recruitment Lead Consultant
17,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Vadodara / Baroda
18,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Institute for Financial Management and Resear
19,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Programme Manager
20,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Chennai
21,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Balu Ramesh
22,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",HR Administrator
23,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Trivandrum
24,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Asif Lucknowi
25,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Director
26,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Indore
27,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",InstaFinancials
28,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Human Resource
29,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Bengaluru / Bangalore
30,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Priyanka Akiri
31,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",HR Manager
32,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Hyderabad
33,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Kalpana Dumpala
34,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Executive Hiring
35,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Hyderabad / Secunderabad
36,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Mubarak
37,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Company HR
38,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Bengaluru / Bangalore
39,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Kushal Rastogi
40,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Company HR
41,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Mumbai
42,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Mahesh Babu Channa
43,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",HR Team Lead
44,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Hyderabad / Secunderabad
45,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",Kapil Devang
46,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",HR Manager
47,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Bhopal
48,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,"Data Science, Machine Learning, Big Data Analy...",Sakshi Chhikara
49,Sunny Sharma,Managing Director - HR,Western Service Providers,"Software Professionals, Engineering, Technical...",Assistant Manager HR

8. Scrape the details of Highest selling novels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [53]:
# Connecting to the webdriver
driver = webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')
driver.get(url)

In [54]:
#Creating empty list
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

#scraping book names data
for i in driver.find_elements_by_xpath("//tbody//tr/td[2]"):
    Book_name.append(i.text)

    
#Scraping author names data
for i in driver.find_elements_by_xpath("//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(1)


#Scraping data of volumes sold
for i in driver.find_elements_by_xpath("//tbody/tr/td[4]"):
    Volumes_sold.append(i.text)

    
#Scraping data of publisher names
for i in driver.find_elements_by_xpath("//tbody/tr/td[5]"):
    Publisher.append(i.text)

    
#Scraping data of genre
for i in driver.find_elements_by_xpath("//tbody/tr/td[6]"):
    Genre.append(i.text)
    
#Creating dataframe for scraped data
Novels=pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

9. Scrape the details most watched tv series of all time from imdb.com.
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [55]:
# Connecting to the webdriver
driver = webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=("https://www.imdb.com/list/ls095964455/")
driver.get(url)

In [56]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

#Scraping data of Names
for i in driver.find_elements_by_xpath("//h3[@class='lister-item-header']/a"):
    Name.append(i.text)

#Scraping data of Year span
for i in driver.find_elements_by_xpath("//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)

#Scraping data of genre
for i in driver.find_elements_by_xpath("//span[@class='genre']"):
    Genre.append(i.text)

#Scraping data of Run time
for i in driver.find_elements_by_xpath("//span[@class='runtime']"):
    Run_time.append(i.text)

#Scraping data of Ratings
for i in driver.find_elements_by_xpath("//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
#Scraping data of votes
for i in driver.find_elements_by_xpath("//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)
    
# Creating dataframe for scraped data
TV_series=pd.DataFrame({})
TV_series['Name'] = Name
TV_series['Year Span'] = Year_span
TV_series['Genre'] = Genre
TV_series['Run Time'] = Run_time
TV_series['Ratings'] = Ratings
TV_series['Votes'] = Votes
TV_series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011â€“2019),"Action, Adventure, Drama",57 min,9.2,"2,000,873"
1,Stranger Things,(2016â€“ ),"Drama, Fantasy, Horror",51 min,8.7,"1,053,125"
2,The Walking Dead,(2010â€“2022),"Drama, Horror, Thriller",44 min,8.2,"951,914"
3,13 Reasons Why,(2017â€“2020),"Drama, Mystery, Thriller",60 min,7.5,"284,504"
4,The 100,(2014â€“2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"244,277"
...,...,...,...,...,...,...
95,Reign,(2013â€“2017),"Drama, Fantasy",42 min,7.4,"48,981"
96,A Series of Unfortunate Events,(2017â€“2019),"Adventure, Comedy, Drama",50 min,7.8,"59,714"
97,Criminal Minds,(2005â€“2020),"Crime, Drama, Mystery",42 min,8.1,"191,187"
98,Scream: The TV Series,(2015â€“2019),"Comedy, Crime, Drama",45 min,7.1,"40,428"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"229,848"

10. Details of Datasets from UCI machine learning repositories.
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code

In [57]:
# Connecting to the webdriver
driver = webdriver.Chrome('chromedriver.exe')

# Getting the webpage of mentioned url 
url=("https://archive.ics.uci.edu/")
driver.get(url)

In [58]:
# Finding view all dataset button from the webpage
viewall_dataset = driver.find_element_by_xpath("//tbody[1]//tr/td[2]/span[2]/a")    
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)

In [59]:
# Fetching page urls of all datasets 
view_list = driver.find_element_by_xpath("/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
list_url = view_list.get_attribute("href")           
driver.get(list_url)

In [60]:
# Fetching urls for each dataset
dataset_url = driver.find_elements_by_xpath("//p[@class='normal']//b/a")    

urls = []     
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [61]:
#Creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

for i in urls:
    driver.get(i)
    time.sleep(3)
    
    #Scraping Dataset name
    try: 
        dataset_name = driver.find_element_by_xpath("//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    time.sleep(2)
    
    #Scraping data type
    try:
        data_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(2)
    
    #scraping Task
    try:
        task = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(2)
    
     # Scraping Attribute type
    try:
        attribute_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    time.sleep(2)
    
    # Scraping No of instances
    try:
        instances = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    time.sleep(2)
    
    # Scraping No of attributes
    try:
        attribute = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    time.sleep(2)
    
    # Scraping year
    try:
        year = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(2)

WebDriverException: Message: unknown error: cannot determine loading status
from disconnected: Unable to receive message from renderer
  (Session info: chrome=102.0.5005.115)
Stacktrace:
Backtrace:
	Ordinal0 [0x0124B8F3+2406643]
	Ordinal0 [0x011DAF31+1945393]
	Ordinal0 [0x010CC748+837448]
	Ordinal0 [0x010BDA12+776722]
	Ordinal0 [0x010BC7C5+772037]
	Ordinal0 [0x010BCDC8+773576]
	Ordinal0 [0x010BCD58+773464]
	Ordinal0 [0x010C29B6+797110]
	Ordinal0 [0x010C2CEA+797930]
	Ordinal0 [0x010BDF9B+778139]
	Ordinal0 [0x010BE4C5+779461]
	Ordinal0 [0x010BE2AF+778927]
	Ordinal0 [0x010BD8A6+776358]
	Ordinal0 [0x010BC7C5+772037]
	Ordinal0 [0x010BCDC8+773576]
	Ordinal0 [0x010C8BE0+822240]
	Ordinal0 [0x010BE0BD+778429]
	Ordinal0 [0x010BEC9A+781466]
	Ordinal0 [0x010BE2CA+778954]
	Ordinal0 [0x010BD8A6+776358]
	Ordinal0 [0x010BC7C5+772037]
	Ordinal0 [0x010BCC9D+773277]
	Ordinal0 [0x010CDF4A+843594]
	Ordinal0 [0x01124D3D+1199421]
	Ordinal0 [0x0111427C+1131132]
	Ordinal0 [0x01124682+1197698]
	Ordinal0 [0x01114096+1130646]
	Ordinal0 [0x010EE636+976438]
	Ordinal0 [0x010EF546+980294]
	GetHandleVerifier [0x014B9612+2498066]
	GetHandleVerifier [0x014AC920+2445600]
	GetHandleVerifier [0x012E4F2A+579370]
	GetHandleVerifier [0x012E3D36+574774]
	Ordinal0 [0x011E1C0B+1973259]
	Ordinal0 [0x011E6688+1992328]
	Ordinal0 [0x011E6775+1992565]
	Ordinal0 [0x011EF8D1+2029777]
	BaseThreadInitThunk [0x76FEFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77817A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77817A6E+238]

In [62]:
# Creating dataframe for scraped data
ML=pd.DataFrame({})
ML['Data Name'] = Dataset_name
ML['Data Type'] = Data_type
ML['Task'] = Task
ML['Attribute type'] = Attribute_type
ML['No of instance'] = No_of_instances
ML['No of attributes'] = No_of_attributes
ML['Year'] = Year
ML

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
342,MiniBooNE particle identification Data Set,Multivariate,Classification,Real,130065,50,2010
343,Miskolc IIS Hybrid IPS Data Set,Text,"Classification, Clustering, Causal-Discovery",Integer,1540,67,2016
344,Mobile Robots Data Set,Domain-Theory,-,"Categorical, Integer, Real",-,-,1995
345,MoCap Hand Postures Data Set,Multivariate,"Classification, Clustering","Integer, Real",78095,38,2016
346,Molecular Biology (Promoter Gene Sequences) Da...,"Sequential, Domain-Theory",Classification,Categorical,106,58,1990